[package]
name = "solana-explorer-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
solana-client = "1.18.16"
solana-sdk = "1.18.16"
spl-token = "4.0.0"
